from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import red, orange, green
from datetime import datetime

def generate_road_health_report(source, destination, potholes, output_path):
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    # ---------- HEADER ----------
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - 50, "ROAD HEALTH COMPLAINT REPORT")

    c.setFont("Helvetica", 11)
    c.drawCentredString(
        width / 2,
        height - 75,
        "AI-Based Pothole Detection & Road Condition Analysis"
    )

    # ---------- META ----------
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 110, f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}")
    c.drawString(50, height - 125, "Generated By: Janadhvani – Smart Road Monitoring System")

    # ---------- ROUTE ----------
    y = height - 170
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Route Information")

    c.setFont("Helvetica", 11)
    c.drawString(70, y - 20, f"Source Location      : {source}")
    c.drawString(70, y - 40, f"Destination Location : {destination}")

    # ---------- SUMMARY ----------
    y -= 90
    total = len(potholes)
    high = sum(1 for p in potholes if p["severity"] == "High")
    medium = sum(1 for p in potholes if p["severity"] == "Medium")
    low = sum(1 for p in potholes if p["severity"] == "Low")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Road Health Summary")

    c.setFont("Helvetica", 11)
    c.drawString(70, y - 20, f"Total Potholes Detected : {total}")
    c.drawString(70, y - 40, f"High Severity           : {high}")
    c.drawString(70, y - 60, f"Medium Severity         : {medium}")
    c.drawString(70, y - 80, f"Low Severity            : {low}")

    # ---------- ROAD CONDITION ----------
    y -= 130
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Overall Road Condition")

    c.setFont("Helvetica", 11)
    if high > 0:
        condition = "CRITICAL – Immediate repair required"
        color = red
    elif medium > 3:
        condition = "MODERATE – Repair recommended"
        color = orange
    else:
        condition = "GOOD – Road is mostly safe"
        color = green

    c.setFillColor(color)
    c.drawString(70, y - 25, condition)
    c.setFillColorRGB(0, 0, 0)

    # ---------- TABLE ----------
    y -= 80
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Detected Pothole Details")

    y -= 25
    c.setFont("Helvetica-Bold", 10)
    c.drawString(50, y, "Latitude")
    c.drawString(130, y, "Longitude")
    c.drawString(220, y, "Severity")
    c.drawString(300, y, "Confidence")
    c.drawString(390, y, "Detected Time")

    c.setFont("Helvetica", 10)
    y -= 15

    for p in potholes:
        if y < 60:
            c.showPage()
            y = height - 50

        c.drawString(50, y, f"{p['lat']:.5f}")
        c.drawString(130, y, f"{p['lon']:.5f}")
        c.drawString(220, y, p["severity"])
        c.drawString(300, y, f"{p['confidence']}")
        c.drawString(390, y, p["time"])
        y -= 15

    # ---------- FOOTER ----------
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(
        width / 2,
        30,
        "This report is generated using AI-based analysis and is intended for official road maintenance purposes."
    )

    c.save()
